### ISSUE TITLE
replace spaces with dashes in generated url

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/blog#105]
If the category has a space in it, the path gets generated with an escaped space in it: 

<img width="1100" alt="screen shot 2017-06-09 at 1 26 13 pm" src="https://user-images.githubusercontent.com/17584/26986866-570983ba-4d17-11e7-94e9-b39202d532ba.png">

We should replace that escaped space with a dash. It looks better.

**Comment by mauro-oto** [comment]
Closing as discussed in https://github.com/ombulabs/blog/pull/119
