### ISSUE TITLE
Update post with latest Rails 5.1 changes

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/blog#106]
In the latest version of Rails (5.1) `any?` and `exists?` are now equally performant. 

Update this post: https://www.ombulabs.com/blog/benchmark/performance/rails/present-vs-any-vs-exists.html

Just wanted to add this here so that we don't forget, @mauro-oto.

**Comment by mauro-oto** [comment]
Updated! https://www.ombulabs.com/blog/benchmark/performance/rails/present-vs-any-vs-exists.html
