### ISSUE TITLE
Use Cloudfront for serving assets 

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/blog#153]
We shouldn't be using Heroku for serving static assets: 

![screen shot 2018-09-11 at 9 12 33 am](https://user-images.githubusercontent.com/17584/45362469-e7051700-b5a2-11e8-9fae-41c07efac747.png)

We should use Cloudfront to do this. It will speed up page load.

**Comment by arielj** [comment]
https://www.pivotaltracker.com/story/show/174887965
